### PR TITLE
Added thank message replies

### PR DESCRIPTION
**Pull request by TECHNOPAWS**
Untested

### CODE REVIEW

**Comment by JadeBetty** [comment]
I think there is a problem, when you use the thank command it would spam.

**Comment by TECHNOPAWS** [comment]
@Ngyang018 Thankyou for pointing that out

**Comment by JadeBetty** [comment]
What if we make it so that it will return when it's in a specific channel? Such as the boosts channel and what channel.

**Comment by NightSling** [comment]
> 

@TECHNOPAWS please update according to this

**Comment by ImagineGamingPlay** [comment]
Outdated

**Pull request closed without merging**
